version: "3"
services:
  api:
    container_name: dev_api_restaurant
    restart: always
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: db_postgres_restaurant
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - base_postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

  

volumes:
  base_postgres_db: